CREATE TABLE IF NOT EXISTS urls (
  id SERIAL PRIMARY KEY,
  user_name TEXT NOT NULL,
  short_code TEXT NOT NULL UNIQUE,
  original_url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);